shows:
  this-week-in-bitcoin:
    show_rss: https://feeds.jupiterbroadcasting.com/twib
    show_url: https://www.thisweekinbitcoin.show/
    jb_url: https://www.jupiterbroadcasting.com/show/this-week-in-bitcoin
    acronym: twib
    name: This Week In Bitcoin
    host_platform: fountain
    dont_override:
      - 0061.md
      - 0060.md
      - 0059.md
      - 0058.md
      - 0057.md
  linux-unplugged:
    show_rss: https://feeds.jupiterbroadcasting.com/lup
    show_url: https:/linux-unplugged.show
    jb_url:  https://www.jupiterbroadcasting.com/show/linux-unplugged
    acronym: lup
    name: LINUX Unplugged
    host_platform: fireside
  the-launch:
    show_rss: https://serve.podhome.fm/rss/04b078f9-b3e8-4363-a576-98e668231306
    show_url: https://www.weeklylaunch.rocks
    jb_url:  https://www.jupiterbroadcasting.com/show/the-launch
    acronym: tl
    name: The Launch ðŸš€
    host_platform: podhome
    dont_override:
      - 0008.md
      - 0007.md
      - 0006.md
      - 0005.md
      - 0004.md
  # self-hosted:
  #   show_rss: https://selfhosted.show/rss
  #   show_url: https://selfhosted.show
  #   jb_url: https://www.jupiterbroadcasting.com/show/self-hosted
  #   acronym: ssh
  #   name: Self-Hosted
  #   host_platform: fireside
  # coder-radio:
  #   show_rss: https://feeds.jupiterbroadcasting.com/coder
  #   show_url: https://coder.show
  #   jb_url:  https://www.jupiterbroadcasting.com/show/coderradio
  #   acronym: cr
  #   name: Coder Radio
  #   host_platform: fireside
  # linux-action-news:
  #   show_rss: https://linuxactionnews.com/rss
  #   show_url: https://linuxactionnews.com
  #   jb_url: https://www.jupiterbroadcasting.com/show/linux-action-news
  #   acronym: LAN
  #   name: Linux Action News
  #   host_platform: fireside
  # jupiter-extras:
  #   show_rss: https://extras.show/rss
  #   show_url: https://extras.show
  #   jb_url: https://www.jupiterbroadcasting.com/show/extras
  #   acronym: JE
  #   name: Jupiter EXTRAS
  #   host_platform: fireside
  # office-hours:
  #   show_rss: https://feeds.us-east-1.linodeobjects.com/office/office.xml
  #   show_url: https://www.officehours.hair
  #   jb_url: https://www.jupiterbroadcasting.com/show/office
  #   acronym: OH
  #   name: Office Hours
  #   host_platform: fireside

# Map usernames of hosts/guests as they appear in Fireside to how we want to
# save them in the new website. This also helps to avoid duplicates
usernames_map:
  chris:
    - chrislas
    - Chris Fisher
  wes:
    - wespayne
    - Wes Payne
  alex:
    - alexktz
    - Alex Kretzschmar
  brent:
    - brentgervais
    - Brent Gervais
  michael:
    - mike
    - Michael Dominick
  danielle-fore:
    - dani
    - daniellefore
  drew-devore:
    - drewdevore
    - drewdvore
    - drewofdoom
  jill-linuxgirl:
    - jilllinuxgirl
  jim-salter:
    - jimsalter
  philip-muller:
    - philipmuller
  popey:
    - alanpope
  wimpy:
    - martinwimpress
  stuart-langridge:
    - stuartlangridge
  tomasz:
    - Tomasz FrÄ…tczak
  michaeltunnell:
    - michaetunnell
    - michael-tunnell
    - Michael Tunnell
  jeff:
    - producer-jeff
    - Producer Jeff
  zach-mitchell:
    - zmitchell
  carlgeorge:
    - carl-george
  jon-seager:
    - jnsgruk

# List of any data filenames (sponsors or people) which shouldn't be
# overridden when scraping latest shows. Any file that was manually edited should
# be added here.
data_dont_override:
  - brent.md
  - chris.md
  - wes.md
  - allanjude.md
  - chzbacon.md
  - ell.md
  - danjohansen.md
  - alex.md
  - catherine-kretzschmar.md
  - jeromelaban.md
  - friends.md
  - joe.md
  - joeres.md
